apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-node-app
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: test-argo-notifications
    notifications.argoproj.io/subscribe.on-sync-failed.slack: test-argo-notifications
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: test-argo-notifications
    notifications.argoproj.io/subscribe.on-created.slack: test-argo-notifications
    notifications.argoproj.io/subscribe.on-deleted.slack: test-argo-notifications
    notifications.argoproj.io/subscribe.on-deployed.slack: test-argo-notifications
    notifications.argoproj.io/subscribe.on-health-degraded.slack: test-argo-notifications
spec:
  destination:
    name: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: nodejs
    repoURL: 'https://github.com/HosHaggag/mn-project.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
