# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# metadata:
#   name: mongodb-kustomize
#   namespace: default
# resources:
#  - statefulset.yaml
# images:
#   - name: mongo
#     newName: mongo
#     newTag: "7.0"


# patches:
#   - target:
#       kind: StatefulSet
#       name: mongod
#     patch: |-
#       - op: replace
#         path: /spec/template/spec/containers/0/image
#         valueFrom:
#           kind: ConfigMap
#           name: mongodb-configmap
#           fieldRef:
#             fieldPath: data.image



apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: mongodb-kustomize
replacements:
  - source:
      kind: ConfigMap
      name: mongodb-configmap
      fieldPath: data.imageName
    target:
      kind: StatefulSet
      name: mongod
      path: spec.template.spec.containers[0].image
      options:
        delimiter: ":"
        index: 0
        create: true
  - source:
      kind: ConfigMap
      name: mongodb-configmap
      fieldPath: data.imageTag
    target:
      kind: StatefulSet
      name: mongod
      path: spec.template.spec.containers[0].image
      options:
        delimiter: ":"
        index: 1
        create: true     
# patches:
#   - target:
#       kind: StatefulSet
#       name: mongod
#     patch: |-
#       - op: replace
#         path: /spec/template/spec/containers/0/image
#         value: mongo:7.0.4
