apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    name: mongo
spec:
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.targetPort }}
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongod
spec:
  serviceName: mongodb-service
  replicas: 3
  selector:
    matchLabels:
      role: mongo
  template:
    metadata:
      labels:
        role: mongo
        environment: test
        replicaset: MainRepSet
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongod-container
          image: {{ .Values.imageName }} : {{ .Values.imageTag }}
          command:
          {{- range .Values.command }}
            - {{ . }}
          {{- end }}
          resources:
            requests:
              cpu: 0.2
              memory: 200Mi
          ports:
            - containerPort: {{ .Values.containerPort }}
          volumeMounts:
            - name: mongodb-persistent-storage-claim
              mountPath: {{ .Values.mountPath }}
  volumeClaimTemplates:
  - metadata:
      name: mongodb-persistent-storage-claim
      annotations:
        volume.beta.kubernetes.io/storage-class: "standard"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.storageSize }}