apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynodejs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mynodejs
  template:
    metadata:
      name: mynodejs-pod
      labels:
        app: mynodejs
    spec:
      containers:
        - name: mynodejs-container
          image: haggagdev/mn-node:1.0.0
          env:
            - name: DBuser
              value: "admin"
            - name: DBpass
              valueFrom:
                secretKeyRef:
                  name: mongo-key
                  key: mongodb-root-password
            - name: DBhosts
              value: "mongo-0.mongo,mongo-1.mongo"
          ports:
            - containerPort: 3000