apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynodejs-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mynodejs
  template:
    metadata:
      name: mynodejs-pod
      labels:
        app: mynodejs
    spec:
      containers:
        - name: mynodejs-container
          image: haggagdev/mn-node:1.0.0
          env:
            - name: DBuser
              value: "demoadmin"
            - name: DBpass
              value: "demopwd"
            - name: DBhosts
              value: "mongo-0.mongodb-service,mongo-1.mongodb-service,mongo-2.mongodb-service"
          ports:
            - containerPort: 3000