# loadbalancer-service.yml
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
  namespace: default
spec:
  selector:
    app: mynodejs
  type: NodePort
  ports:
  - protocol: TCP
    port: 80  # External port
    targetPort: 3000     
